### ISSUE TITLE
DebugRender nullptr 접근 문제

### ISSUE THREAD

**Issue by pasongsj** [BeNew98/DeathDoor#316]
## 목적
>
## 작업 상세 내용
- [ ] update 중 death된 개체를 DebugRender에서 랜더하려 할 때 문제가 터짐 null체크가 안된 것으로 추정
## 참고 사항 
![스크린샷 2023-11-04 182108](https://github.com/BeNew98/DeathDoor/assets/43164999/872f8421-d51c-49fa-8f21-57257a8ddd4c)
![스크린샷 2023-11-04 182145](https://github.com/BeNew98/DeathDoor/assets/43164999/6de91754-c3ae-4ff8-a452-0b33b797e628)

**Comment by BeNew98** [comment]
버섯이 Component를 death안시키고 다른걸로 시켜서 생긴문제 수정완료
